name: Static Checks 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  static-checks:
    name: 'Static checks'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Scony/godot-gdscript-toolkit@master
    - run: gdformat godot_project/scripts/
    - run: gdlint godot_project/scripts/
    - run: gdradon cc godot_project/scripts/
